### ISSUE TITLE
-dropViewController:forPieceWillClose:afterSuccessfulDrop: always reports failure

### ISSUE THREAD

**Issue by Boerworz** [allihoopa/Allihoopa-iOS#17]
Regardless of if the user taps "Cancel" before dropping or "Done" after a successful drop, the last argument to `-[AHADropDelegate dropViewController:forPieceWillClose:afterSuccessfulDrop:]` is always `NO`. The argument should be `YES` if the user taps "Done" after a successful drop.

**Comment by tomhai** [comment]
This has been fixed in the release version 2.0.0
