### ISSUE TITLE
Update build on this & drop buttons to new copy & icon

### ISSUE THREAD

**Issue by johanrothoff** [allihoopa/Allihoopa-iOS#25]
**Tasks**
* Update copy from “Build on this” to “Pick Up”
* Update to new icons 

**Instances**

- [x] Drop screen, update icon [Zeplink](https://zpl.io/E1KO9)

**Comment by Boerworz** [comment]
This was fixed in ab642d709c75b64af2593f5e2c696c0fd8fa55fd, which was part of the [v2.1.2 release](https://github.com/allihoopa/Allihoopa-iOS/releases/tag/v2.1.2).
