### ISSUE TITLE
Update style of buttons 

### ISSUE THREAD

**Issue by johanrothoff** [allihoopa/Allihoopa-iOS#26]
**Tasks**

* Locate all instances
* Round corners
* Title Case instead of ALL CAPS
* Bold text on primary buttons
* Regular on secondary buttons

**Instances**

- [ ] Install Allihoopa-screen [Zeplink](https://zpl.io/Z22FXSD)

**Comment by JagCesar** [comment]
This is fixed now, closing issue :)
