### ISSUE TITLE
Out of range tempos fail without programmer error notification when creating pieces

### ISSUE THREAD

**Issue by dgventura** [allihoopa/Allihoopa-iOS#3]
Initialise an AHAFixedTempo with a tempo of 150000, then try to hand this to AHADropPieceData as the tempo.  The AHADropPieceData comes back nil without warning or error.  Maybe invalid tempos should throw an exception?

**Comment by mhallin** [comment]
`AHADropPieceData`'s constructor should return nil in these cases, but the error parameter _should_ be set. We have a test case for this here: https://github.com/allihoopa/AllihoopaCore-ObjC/blob/master/Tests/ValidationTests.m#L155-L165. Can you try updating to 1.0.0 and see if the issue persists?
