### ISSUE TITLE
Drop done view doesn't work in landscape

### ISSUE THREAD

**Issue by JagCesar** [allihoopa/Allihoopa-iOS#39]
Drop done view isn't properly setup to support landscape mode. This is what it looks like today:

![simulator screen shot 24 aug 2017 14 44 54](https://user-images.githubusercontent.com/923548/29667445-bc8ff286-88dc-11e7-8191-96a214637f95.png)

This is what it looks like in portrait mode:

![simulator screen shot 24 aug 2017 14 44 53](https://user-images.githubusercontent.com/923548/29667458-c56d835a-88dc-11e7-84e7-4716b3e42c56.png)

**Comment by Boerworz** [comment]
This was fixed implicitly when we redesigned the view for release [3.1.0](https://github.com/allihoopa/Allihoopa-iOS/releases/tag/v3.1.0). Closing.
