### ISSUE TITLE
"Log in" button hidden on login screen

### ISSUE THREAD

**Issue by johnytex** [allihoopa/Allihoopa-iOS#46]
If I try to log in via Take I can't see the log in button:
![img_4940](https://user-images.githubusercontent.com/1251574/30051996-53674d9e-9224-11e7-992c-c10af304f4e3.PNG)

Furthermore, if I press "Done" on the on-screen keyboard after entering my credentials I can't scroll down. Focusing on one of the input fields allows me to see the Login button and restores scrolling (sometimes?)

Steps to reproduce:

1. Push Login in the Take "welcome" screen
2. Tap the username text field
3. Enter username / password
4. Press the "Done" button on the on-screen keyboard
5. Scrolling should stop working

**Comment by leonathorst** [comment]
Fixed
