### ISSUE TITLE
Player doesn't work on iOS 9

### ISSUE THREAD

**Issue by JagCesar** [allihoopa/Allihoopa-iOS#49]
The player that was added a few weeks ago is using SDK functions that aren't available in iOS 9, which makes it crash.

Let's fix it!

![giphy](https://user-images.githubusercontent.com/923548/30488251-190cedb0-9a36-11e7-81df-6a94b11deff7.gif)

**Comment by Boerworz** [comment]
A fix has been implemented in #50 and will be made available in the next release :tada:

**Comment by Boerworz** [comment]
The fix was released in [version 2.4.0](https://github.com/allihoopa/Allihoopa-iOS/releases/tag/v2.4.0).
