### ISSUE TITLE
Profile isn't loading

### ISSUE THREAD

**Issue by rene-hasoon** [allihoopa/Allihoopa-iOS#54]
![image](https://user-images.githubusercontent.com/27866487/30904108-3ba8e63c-a371-11e7-96fa-5e0664200a3c.png)

**Comment by leonathorst** [comment]
@rene-hasoon This doesn't look like a profile view in any of our apps. Can you try to find out exactly what they do to get to this screen?

**Comment by rene-hasoon** [comment]
Weird. I wrote to him this morning for an update, I'll update you once I find out!

**Comment by leonathorst** [comment]
@rene-hasoon Did you ever hear back on this? If not, we should close it.

**Comment by rene-hasoon** [comment]
Haven’t heard anything back!
